task/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from manager import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('registration/', views.registration.as_view(), name='registration')

]

# TODO: Переностроить урл адреса

urlpatterns += [
    path('dictionary/', include('manager.url'))
]

urlpatterns += [
    path('', RedirectView.as_view(url='/dictionary/', permanent=True))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

manager/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a name for a certain category of words (opt.).', null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('categories_detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Dict(models.Model):
    eng_word = models.CharField(max_length=100, help_text='Enter english word here.')
    transcript = models.CharField(max_length=150, null=True, blank=True, help_text='Enter transcription of word here '
                                                                                   '(optional).')
    rus_word = models.CharField(max_length=200, help_text='Enter russian translate.')
    exemp = models.TextField(null=True, blank=True, help_text='Enter examples for word (opt.).')
    category = models.ManyToManyField(Category, help_text='Select a category')
    executor = models.ForeignKey(User, on_delete=models.CASCADE)
    create_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.eng_word

    def get_absolute_url(self):
        return reverse('word-detail', args=[str(self.id)])

manager/forms.py
from django.contrib.auth.models import User
from django import forms


class UserRegistrForm(forms.ModelForm):
    password = forms.CharField(label='Passwords', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat passwords', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['passwords'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

manager/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView
from django.views import generic
from .models import Dict as Dict_Model, Category as Category_Model


# Create your views here.


def index(request):
    return render(
        request, 'index.html'
    )


class registration(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/registration.html'


class words(LoginRequiredMixin, generic.ListView):
    login_url = reverse_lazy('login')
    model = Dict_Model
    template_name = 'words.html'

    def get_queryset(self):
        return Dict_Model.objects.filter(executor = self.request.user)


class categories(LoginRequiredMixin, generic.ListView):
    model = Category_Model
    login_url = reverse_lazy('login')
    template_name = 'categories.html'
    def get_queryset(self):
        return Category_Model.objects.filter(owner = self.request.user)


class categories_detail(LoginRequiredMixin, generic.DetailView):
    login_url = reverse_lazy('login')
    model = Dict_Model
    template_name = 'categories_detail.html'

manager/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block title %}<title>Dictionary</title>{% endblock %}
  </head>
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    {% block navbar %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Pet project</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'words' %}">My  Dictionary</a>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'categories' %}">My categories</a>
        </li>
                <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
  {% endblock %}
    {% block content %}{% endblock %}
  </body>
</html>

manager/templates/categories.html
{% extends "base.html" %}
{% block content %}
    <h1>All your category:</h1>
    {% if category_list %}
    <ul>
        {% for category in category_list %}
        <li>
            <a href="{{category.get_absolute_url}}">{{category.name}}</a>
        </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>You dont write a single category :(</p>
    {% endif %}
{% endblock %}

manager/templates/categories_detail.html
{% extends "base.html" %}
{% block content %}
{% if dict_list %}
    <h1>Category: {{Dict.category}}</h1>
    <ul>
    <ul class="list-group list-group-horizontal">
            <li class="list-group-item">English word</li>
            <li class="list-group-item">Transcription</li>
            <li class="list-group-item">Translate</li>
    </ul>
        {% for word in dict_list %}
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item">{{word.eng_word}}</li>
            <li class="list-group-item">{{word.transcript}}</li>
            <li class="list-group-item">{{word.rus_word}}</li>
        </ul>
        {% endfor %}
    </ul>
    {% else %}
        <p>You don't write a single word :(</p>
    {% endif %}
{% endblock %}

manager/templates/index.html
{% extends "base.html" %}
{% block content %}
{% if user.is_authenticated %}
<h1>Test</h1>

{% else %}
<h4>To use the site, please log in or register</h4>
<a href="{% url 'login'%}?next={{request.path}}">Login</a>
<a href="{% url 'registration'%}?next={{request.path}}">Registration</a>
{% endif %}
{% endblock %}

manager/templates/words.html
{% extends "base.html" %}
{% block content %}
    <h1>All your words:</h1>
    {% if dict_list %}
    <ul>
    <ul class="list-group list-group-horizontal">
            <li class="list-group-item">English word</li>
            <li class="list-group-item">Transcription</li>
            <li class="list-group-item">Translate</li>
    </ul>
        {% for word in dict_list %}
        <ul class="list-group list-group-horizontal">
            <li class="list-group-item">{{word.eng_word}}</li>
            <li class="list-group-item">{{word.transcript}}</li>
            <li class="list-group-item">{{word.rus_word}}</li>
        </ul>
        {% endfor %}
    </ul>
    {% else %}
        <p>You don't write a single word :(</p>
    {% endif %}
{% endblock %}